name: ClangFormat

concurrency:
  group: ${{ github.workflow }}#${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main
      - v2.x

jobs:
  Code_Format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run clang-format
      run: |
        bash bin/format.sh
